00:28:06.989 Running build in Washington, D.C., USA (East) – iad1
00:28:06.989 Build machine configuration: 2 cores, 8 GB
00:28:07.130 Cloning github.com/merhelpdesk-ops/merswap (Branch: main, Commit: 47bc64f)
00:28:24.665 Cloning completed: 17.534s
00:28:25.017 Restored build cache from previous deployment (E3nMfNPfhJrNNYrrcyRrTDdNxCHB)
00:28:25.408 Running "vercel build"
00:28:25.427 Vercel CLI 54.9.0
00:28:25.928 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
00:28:25.928 Using pnpm@10.x based on project creation date
00:28:25.929 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
00:28:26.032 Installing dependencies...
00:28:26.717 Lockfile is up to date, resolution step is skipped
00:28:27.189 Already up to date
00:28:27.674 
00:28:27.701 ╭ Warning ─────────────────────────────────────────────────────────────────────╮
00:28:27.702 │                                                                              │
00:28:27.702 │   Ignored build scripts: bigint-buffer@1.1.5, blake-hash@2.0.0,              │
00:28:27.703 │   bufferutil@4.0.8, esbuild@0.23.1, keccak@3.0.3, protobufjs@7.4.0,          │
00:28:27.703 │   tiny-secp256k1@1.1.7, usb@2.15.0, utf-8-validate@5.0.10.                   │
00:28:27.703 │   Run "pnpm approve-builds" to pick which dependencies should be allowed     │
00:28:27.703 │   to run scripts.                                                            │
00:28:27.704 │                                                                              │
00:28:27.704 ╰──────────────────────────────────────────────────────────────────────────────╯
00:28:27.707 Done in 1.6s using pnpm v10.28.0
00:28:27.724 Detected Next.js version: 13.5.6
00:28:27.776 Running "pnpm run build"
00:28:28.047 
00:28:28.047 > @jup-ag/plugin@1.0.15 build /vercel/path0
00:28:28.048 > next build
00:28:28.048 
00:28:29.188    Linting and checking validity of types ...
00:28:34.363 
00:28:34.363 ./src/components/screens/WalletScreen.tsx
00:28:34.371 57:19  Warning: Do not use `<img>` element. Use `<Image />` from `next/image` instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
00:28:34.371 
00:28:34.372 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
00:28:34.772    Creating an optimized production build ...
00:28:38.445 Browserslist: caniuse-lite is outdated. Please run:
00:28:38.446   npx browserslist@latest --update-db
00:28:38.446   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
00:28:41.912 Browserslist: caniuse-lite is outdated. Please run:
00:28:41.912   npx update-browserslist-db@latest
00:28:41.913   Why you should do it regularly: https://github.com/browserslist/update-db#readme
00:28:50.203  ✓ Compiled successfully
00:28:50.204    Collecting page data ...
00:28:50.873 bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
00:28:51.972    Generating static pages (0/3) ...
00:28:52.011 Your application is presently configured to use the `UnsafeBurnerWalletAdapter`. Find and remove it, then replace it with a list of adapters for wallets you would like your application to support. See https://github.com/anza-xyz/wallet-adapter#usage for an example.
00:28:52.012 Error: useLanguage must be used within a LanguageProvider
00:28:52.013     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.013     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.013     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.014     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.014     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.014     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.015     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.016     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.016     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.017     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.022 
00:28:52.023 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
00:28:52.023 Error: useLanguage must be used within a LanguageProvider
00:28:52.023     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.024     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.024     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.024     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.025     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.025     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.025     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.026     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.026     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.026     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.070 Your application is presently configured to use the `UnsafeBurnerWalletAdapter`. Find and remove it, then replace it with a list of adapters for wallets you would like your application to support. See https://github.com/anza-xyz/wallet-adapter#usage for an example.
00:28:52.071 Error: useLanguage must be used within a LanguageProvider
00:28:52.071     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.072     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.072     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.072     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.072     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.073     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.074     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.074     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.074     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.074     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.074 
00:28:52.074 Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
00:28:52.074 Error: useLanguage must be used within a LanguageProvider
00:28:52.074     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.074     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.074     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.074     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.074     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.074     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.074     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.083     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.083     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.083     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.088 Your application is presently configured to use the `UnsafeBurnerWalletAdapter`. Find and remove it, then replace it with a list of adapters for wallets you would like your application to support. See https://github.com/anza-xyz/wallet-adapter#usage for an example.
00:28:52.089 Error: useLanguage must be used within a LanguageProvider
00:28:52.089     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.089     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.089     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.089     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.089     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.089     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.089     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.089     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.089     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.089     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.089 
00:28:52.089 Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
00:28:52.089 Error: useLanguage must be used within a LanguageProvider
00:28:52.089     at useLanguage (/vercel/path0/.next/server/chunks/250.js:35:14509)
00:28:52.089     at __WEBPACK_DEFAULT_EXPORT__ (/vercel/path0/.next/server/chunks/250.js:1:243)
00:28:52.089     at Wc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
00:28:52.089     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
00:28:52.089     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
00:28:52.089     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.089     at bd (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
00:28:52.090     at Z (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
00:28:52.090     at $c (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
00:28:52.090     at Zc (/vercel/path0/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
00:28:52.090 
 ✓ Generating static pages (3/3) 
00:28:52.092 
00:28:52.092 > Export encountered errors on following paths:
00:28:52.093 	/
00:28:52.093 	/_error: /404
00:28:52.093 	/_error: /500
00:28:52.157  ELIFECYCLE  Command failed with exit code 1.
00:28:52.179 Error: Command "pnpm run build" exited with 1
